# Generated by Django 4.2.16 on 2024-11-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('weight', models.IntegerField(verbose_name='Вес в кг')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='Производитель')),
                ('lattice', models.CharField(max_length=100, verbose_name='Решётка')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('availability', models.IntegerField(verbose_name='Наличие')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Хоспер',
                'verbose_name_plural': 'Хосперы',
            },
        ),
        migrations.CreateModel(
            name='Smokehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('weight', models.IntegerField(verbose_name='Вес в кг')),
                ('lattice', models.CharField(max_length=100, verbose_name='Решётка')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('availability', models.IntegerField(verbose_name='Наличие')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Коптильня',
                'verbose_name_plural': 'Коптильни',
            },
        ),
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('material', models.CharField(max_length=100, verbose_name='Материал')),
                ('weight', models.IntegerField(verbose_name='Вес в кг')),
                ('descriptions', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('availability', models.IntegerField(verbose_name='Наличие')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Подставка',
                'verbose_name_plural': 'Подставки',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('hosper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='unit.hosper')),
                ('smokehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='unit.smokehouse')),
                ('stand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='unit.stand')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
            },
        ),
        migrations.AddField(
            model_name='hosper',
            name='smokehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unit.smokehouse', verbose_name='Коптильня'),
        ),
        migrations.AddField(
            model_name='hosper',
            name='stand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unit.stand', verbose_name='Подставка'),
        ),
    ]
